FROM python:3.10.4

MAINTAINER Eunji Park <izzy@minerinc.io>

WORKDIR /shotag/backend/

RUN pip3 install django


COPY requirements.txt /shotag/backend/
RUN pip3 install -r requirements.txt

COPY . .

# manage.py를 실행할 수 있는 디렉토리로 이동합니다.

CMD ["python3", "nlpproject/manage.py", "runserver", "0.0.0.0:8000"]

EXPOSE 8000