FROM python:3.8.16

MAINTAINER Eunji Park <izzy@minerinc.io>

WORKDIR /shotag/nlpserver/

RUN pip3 install django


COPY requirements.txt /shotag/nlpserver/
RUN pip3 install -r requirements.txt

COPY . .

# manage.py를 실행할 수 있는 디렉토리로 이동합니다.

CMD ["python3", "api/manage.py", "runserver", "0.0.0.0:8000"]

EXPOSE 8000